### ISSUE TITLE
the text isn't correct

### ISSUE THREAD

**Issue by YehudaMorad** [linnovate/root#1357]
![image](https://user-images.githubusercontent.com/40392773/48839487-5a41bb00-ed94-11e8-9f54-b2d8d0af1cb6.png)
change the text in the marked place. 
the correct text is "Duplicate task"

**Comment by chensabag** [comment]
in addition- need to change the icon of duplicate task

**Comment by manmorc** [comment]
@YehudaMorad what is the wright translate for the "duplicate task" ?
"משימה כפולה" is wrong?

**Comment by AviramAshkenazi** [comment]
@manmorc 
it's right translating but the action should call "שכפל משימה".

**Comment by abrahamos** [comment]
Fixed.

**Comment by yaronmir** [comment]
still exists 
![image](https://user-images.githubusercontent.com/38312178/49788612-72bd4980-fd32-11e8-88ed-42f64befff32.png)
