### ISSUE TITLE
documents tab( in an entity) bugs

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1395]
after adding a doc to an entity, trying to view it after pressing the preview button, doesnt work
![image](https://user-images.githubusercontent.com/38312178/49730697-d76c9b80-fc81-11e8-8204-90a98e49eb52.png)

and trying to download the document using the preview screen results in a restricted access message to pop up 
![image](https://user-images.githubusercontent.com/38312178/49730747-ff5bff00-fc81-11e8-858a-2fee8224aec3.png)

**Comment by abrahamos** [comment]
Looks duplicate of #1348

**Comment by yaronmir** [comment]
its not a duplicate since this inst a visual bug

**Comment by abrahamos** [comment]
I see that there are specific forbidden characters, that when used in file names they cause these kind of problems.
This behavior is due to the logic written in this file caused by [this function](https://github.com/linnovate/root/blob/release/2.0.6/packages/custom/icu/server/controllers/attachments.js#L356).
But in the given example (`gfgdg.txt`), there shouldn't be any problem...
Can you please make sure again with normal filename?

**Comment by chensabag** [comment]
the files are same
![image](https://user-images.githubusercontent.com/25196313/50421754-7fba5c80-084b-11e9-86be-95c287a4b6e7.png)

**Comment by abrahamos** [comment]
Fixed by 6a74d9d0957dd6277c6625b97093b1a14a479da5

**Comment by AviramAshkenazi** [comment]
@abrahamos  still happens and now even click on the button lead to nothing.
