### ISSUE TITLE
when assigning a project to a task/ office to a folder/ folder to a document, higher permissions are replaced with lower ones

### ISSUE THREAD

**Issue by yaronmir** [linnovate/root#1615]
- [ ] tasks
open a new task
assign to it a project you have lower permissions in it(commenter/viewer)
the editor perms are replaced with the lower permission

- [ ] folders
open a new folder
assign to it an office you have lower permissions in it(commenter/viewer)
the editor perms are replaced with the lower permission

- [ ] documents (refer to #1591 )

**Comment by manmorc** [comment]
@yaronmir fixed in https://github.com/linnovate/root/pull/1607

**Comment by yaronmir** [comment]
@AvrahamO this isnt fixed, but instead it of lowering the permissions, it deletes the current permissions, and the office/project selection isnt saved after refreshing the page

before selection:
![image](https://user-images.githubusercontent.com/38312178/53340510-d7d81280-3911-11e9-9702-01f9c1185356.png)

after selection:
![image](https://user-images.githubusercontent.com/38312178/53340565-01913980-3912-11e9-9354-a2635e0aaff2.png)

**Comment by manmorc** [comment]
@yaronmir first one is the result of #1307

**Comment by yaronmir** [comment]
fixed
