### ISSUE TITLE
profile dialog issues

### ISSUE THREAD

**Issue by nevos** [linnovate/root#682]
no indication (in dialog) that anything changed after reset or upload new image
![image](https://user-images.githubusercontent.com/1281931/37952754-8adc1b40-31a9-11e8-8e24-5192763ccce9.png)

hebrew mix in profile
![image](https://user-images.githubusercontent.com/1281931/37952769-99217aa6-31a9-11e8-82d1-55b8a8098591.png)

**Comment by manmorc** [comment]
fixed in https://github.com/linnovate/root/pull/683

**Comment by nevos** [comment]
Still not resolved - 
ailed to load resource: the server responded with a status of 502 (Bad Gateway)
angular.min.js?asfddholxr:107 TypeError: Cannot convert undefined or null to object
    at Object.resetAvatar (users.service.js:142)
    at r.$scope.resetAvatar (modal.directive.js:334)
    at fn (eval at compile (angular.min.js?asfddholxr:213), <anonymous>:4:525)
    at e (angular.min.js?asfddholxr:254)
    at r.$eval (angular.min.js?asfddholxr:133)
    at r.$apply (angular.min.js?asfddholxr:134)
    at HTMLButtonElement.<anonymous> (angular.min.js?asfddholxr:254)
    at HTMLButtonElement.dispatch (jquery.min.js?asfddholxr:2)
    at HTMLButtonElement.y.handle (jquery.min.js?asfddholxr:2)

**Comment by nevos** [comment]
I think it makes the app crash - server log:
root-app_1      | GET /icu/components/modal-directive/modalUser.html 200 - - 3.285 ms
root-app_1      | GET /api/users/me 304 - - 1.519 ms
root-app_1      | current user
root-app_1      | {"__v":0,"uid":"8f144de0-325d-11e8-9b80-07094b6c1f9f","id":"x@gmail.com","name":"x@gmail.com","email":"x@gmail.com","username":"x@gmail.com","_id":"5abb4abc8e3c771100a5f326","GetMailEveryDayAboutMyTasks":"no","GetMailEveryWeekAboutGivenTasks":"no","GetMailEveryWeekAboutMyTasks":"no","provider":"local","roles":["authenticated"]}
root-app_1      | events.js:141
root-app_1      |       throw er; // Unhandled 'error' event
root-app_1      |       ^
root-app_1      | 
root-app_1      | Error: EACCES: permission denied, open '/usr/src/app/packages/core/users/public/assets/img/avatar/5abb4abc8e3c771100a5f326.jpeg'
root-app_1      |     at Error (native)
root-app_1      | [07:57:07] [nodemon] app crashed - waiting for file changes before starting...

**Comment by nevos** [comment]
@manmorc - **pressing RESET causes client side error:**
TypeError: Cannot convert undefined or null to object
    at Object.resetAvatar (users.service.js:142)
    at r.$scope.resetAvatar (modal.directive.js:334)
    at fn (eval at compile (angular.js:13365), <anonymous>:4:525)
    at e (angular.js:23613)
    at r.$eval (angular.js:16052)
    at r.$apply (angular.js:16152)
    at HTMLButtonElement.<anonymous> (angular.js:23618)
    at HTMLButtonElement.dispatch (jquery.min.js?l5yez0n3ik9:2)
    at HTMLButtonElement.y.handle (jquery.min.js?l5yez0n3ik9:2)

**Comment by nevos** [comment]
clicking REPLACE casued: 
client console:
angular.js:10765 POST http://hroot.hrm.demo.linnovate.net/api/avatar 502 (Bad Gateway)
**And Server console shows application crashed**
root-app_1      | Error: EACCES: permission denied, open '/usr/src/app/packages/core/users/public/assets/img/avatar/5abb4abc8e3c771100a5f326.jpeg'
root-app_1      |     at Error (native)
root-app_1      | [08:05:08] [nodemon] app crashed - waiting for file changes before starting...
